require('optmatch')
data(plantdist)
summary(fullmatch(plantdist<10))
data(nuclearplants)
psm <- glm(pr~.-(pr+cost), family=binomial(), data=nuclearplants)
psd <- pscore.dist(psm)
psfm <- fullmatch(psd/(psd<.25))
summary(psfm)
psd$m[1,] <- psd$m[1,] + rep(100,22)
summary(pairmatch(psd, controls=2))
summary(psfm, propensity.model=psm)
require('RItools')
summary(psfm, propensity.model='foo')
summary(psfm, propensity.model=psm)

